name: localhands_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.1 
  animated_text_kit: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/image.png
    - assets/logo.jpeg
    - assets/electrician.json
    - assets/painter.json
    - assets/plumber.json