name: localhands_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0
  

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.1
   
  animated_text_kit: ^4.3.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  google_fonts: ^6.3.2
  table_calendar: ^3.1.0  
  iconsax: ^0.0.8
  curved_navigation_bar: ^1.0.3
  firebase_core: ^3.6.0
  syncfusion_flutter_charts: ^28.1.38
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  file_picker: ^10.3.3
  open_file: ^3.5.10
  animations: ^2.1.0
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.13.1
  fl_chart: 0.68.0
  shimmer: ^3.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_generative_ai: ^0.4.7





  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:

  uses-material-design: true
  assets:
    - assets/image.png
    - assets/logo.jpeg
    - assets/electrician.json
    - assets/painter.json
    - assets/plumber.json
    - assets/bb987eec-c72f-4b6a-b8e5-383879c85b97.jpg
    - assets/painter.jpg
    
    - assets/3781959.jpg
    - assets/logoflutter.png
    - assets/profile.jpg
    - assets/offer.png
    - assets/housemaid.jpeg
    - assets/child-care.jpeg
    - assets/women_salon.jpeg
    - assets/men_salon.jpeg
    - assets/explore.jpeg
    - assets/images/explore.jpeg
    - assets/manicure.jpeg
    - assets/pedicure.jpeg
    - assets/haircare.jpeg
    - assets/waxing.jpeg
    - assets/massage.jpeg
    - assets/offerdoorbell.jpeg
    - assets/plumber.jpeg
    - assets/plum6.jpeg
    - assets/plum1.jpeg
    - assets/plum2.jpeg
    - assets/plum3.jpeg
    - assets/plum4.jpeg
    - assets/plum5.jpeg
    - assets/maid1.jpg
    - assets/maid2.jpg
    - assets/maid3.jpg
    - assets/download.jpg
    - assets/beauty.jpg
    - assets/b1.jpg
    - assets/b2.jpg
    - assets/b3.jpg
    - assets/beaty1.jpg
    - assets/ocean.jpg
    - assets/maid.jpg
    - assets/caterings.jpg
    - assets/diwali.jpg
    - assets/child-care.jpeg
    - assets/plumberwallpaper.jpg
    - assets/logoicon.png
    - assets/profilepic.jpg

    # ðŸ‘‡ Add your services folder (includes all 5 JPGs)
    - assets/services/


    - assets/login/help.json
    - assets/login/hashtag loader.json